platform :ios, '26.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'FitnessAIApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true
  )

  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  post_install do |installer|
    react_native_post_install(installer, :mac_catalyst_enabled => false)
  end
end
